# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    tags: "*"
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -o sukeb
    - name: Package Zip
      run: zip -r sukeb.zip sukeb/*
      
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ github.ref_name }}
        make_latest: true
        files: sukeb.zip
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker release
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v6
      with:
        context: ./
        platforms: linux/amd64,linux/arm64
        push: true
        tags: lzw723/sukeb:latest,lzw723/sukeb:${{ github.ref_name }}
    - name: Docker nightly
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v6
      with:
        context: ./
        platforms: linux/amd64,linux/arm64
        push: true
        tags: lzw723/sukeb:nightly,lzw723/sukeb:nightly-${{ github.sha }}